name: "Generate Python Client from OpenAPI"
description: "Generates a Python client package from an OpenAPI document using the openapi-python-client project"
branding:
  icon: "target"
  color: "green"

inputs:
  openapi-python-client-version:
    description: The version of openapi-python-client to use
    required: false
    default: NOT_SPECIFIED
  openapi-file:
    description: The path to the OpenAPI document to generate a client library for e.g. docs/openapi.json
    required: false
    default: openapi.json
  openapi-url:
    description: The url of the OpenAPI document to generate a client library for e.g. https://petstore3.swagger.io/api/v3/openapi.json
    required: false
    default: NOT_SPECIFIED
  config-file:
    description: Path to the config file to be passed along to openapi-python-client
    required: false
    default: NOT_SPECIFIED

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.openapi-python-client-version }}
    - ${{ inputs.openapi-file }}
    - ${{ inputs.openapi-url }}
    - ${{ inputs.config-file }}
